version: 2.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - dev
  - master
  - core

image:
- Ubuntu
- Visual Studio 2017

max_jobs: 1

for:
-
  matrix:
    only:
      - image: Ubuntu
  install:
  - bash: >-
      mkdir .dotnet && 
      chmod +x dotnet-install.sh && 
      ./dotnet-install.sh --version 2.1.400 --install-dir .dotnet && 
      PATH=".dotnet:"$PATH && dotnet --info 
  build_script:
  - bash: dotnet build WebJobs.Script.sln
  test:
  - bash: >-
      set -e
      
      dotnet test test/WebJobs.Script.Tests -v q
      dotnet test test/WebJobs.Script.Scaling.Tests -v q
      dotnet test test/WebJobs.Script.Tests.Integration -v q --filter Category!=E2E
      dotnet test test/WebJobs.Script.Tests.Integration -v q --filter Group=CSharpEndToEndTests
      dotnet test test/WebJobs.Script.Tests.Integration -v q --filter Group=NodeEndToEndTests
      dotnet test test/WebJobs.Script.Tests.Integration -v q --filter Group=DirectLoadEndToEndTests
      dotnet test test/WebJobs.Script.Tests.Integration -v q --filter Group=FSharpEndToEndTests
      dotnet test test/WebJobs.Script.Tests.Integration -v q --filter Group=LanguageWorkerSelectionEndToEndTests
      dotnet test test/WebJobs.Script.Tests.Integration -v q --filter Group=NodeScriptHostTests
      dotnet test test/WebJobs.Script.Tests.Integration -v q --filter Group=RawAssemblyEndToEndTests
      dotnet test test/WebJobs.Script.Tests.Integration -v q --filter Group=SamplesEndToEndTests
      dotnet test test/WebJobs.Script.Tests.Integration -v q --filter Group=StandbyModeEndToEndTests
      dotnet test test/WebJobs.Script.Tests.Integration -v q --filter Group=ContainerInstanceTests

-
  matrix:
    only:
      - image: Visual Studio 2017
  init:
  - ps: |
      if ($env:FUNCTIONS_NIGHTLY -eq "1") {
        $version = Get-Date -Format "yyyyMMdd-HHmm"
        Update-AppveyorBuild -Version $version -Message "Functions Scheduled Build"
      }  
  clone_folder: c:\azure-webjobs-sdk-script
  install:
  - ps: >-
      $env:CommitHash = "$env:APPVEYOR_REPO_COMMIT"

      Install-Product node 10.0.0 x86
  build_script:
  - ps: |
      $hasTag = Test-Path env:APPVEYOR_REPO_TAG_NAME
      .\build.ps1 -buildNumber "$env:APPVEYOR_BUILD_NUMBER" -includeVersion (!$hasTag)
  after_build:
  - ps: >
      $bypassPackaging = $env:APPVEYOR_PULL_REQUEST_NUMBER -and -not $env:APPVEYOR_PULL_REQUEST_TITLE.Contains("[pack]")

      if ($bypassPackaging) {
        Write-Host "Bypassing artifact publishing for pull request." -ForegroundColor Yellow
      } else {
        Get-ChildItem buildoutput\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName "Binaries" }

        Get-ChildItem buildoutput\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName "Runtime" }
      }
  test_script:
  - ps: >
      .\run-tests.ps1
